#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskList.NET.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ToDoList")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertToDo(ToDo instance);
    partial void UpdateToDo(ToDo instance);
    partial void DeleteToDo(ToDo instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ToDoListConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ToDo> ToDos
		{
			get
			{
				return this.GetTable<ToDo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ToDos")]
	public partial class ToDo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TodoId;
		
		private string _TodoDescMain;
		
		private string _TodoDescSecondary;
		
		private System.Nullable<System.DateTime> _TodoDueDate;
		
		private System.Nullable<bool> _TaskCompleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTodoIdChanging(int value);
    partial void OnTodoIdChanged();
    partial void OnTodoDescMainChanging(string value);
    partial void OnTodoDescMainChanged();
    partial void OnTodoDescSecondaryChanging(string value);
    partial void OnTodoDescSecondaryChanged();
    partial void OnTodoDueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTodoDueDateChanged();
    partial void OnTaskCompletedChanging(System.Nullable<bool> value);
    partial void OnTaskCompletedChanged();
    #endregion
		
		public ToDo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TodoId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TodoId
		{
			get
			{
				return this._TodoId;
			}
			set
			{
				if ((this._TodoId != value))
				{
					this.OnTodoIdChanging(value);
					this.SendPropertyChanging();
					this._TodoId = value;
					this.SendPropertyChanged("TodoId");
					this.OnTodoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TodoDescMain", DbType="VarChar(50)")]
		public string TodoDescMain
		{
			get
			{
				return this._TodoDescMain;
			}
			set
			{
				if ((this._TodoDescMain != value))
				{
					this.OnTodoDescMainChanging(value);
					this.SendPropertyChanging();
					this._TodoDescMain = value;
					this.SendPropertyChanged("TodoDescMain");
					this.OnTodoDescMainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TodoDescSecondary", DbType="VarChar(50)")]
		public string TodoDescSecondary
		{
			get
			{
				return this._TodoDescSecondary;
			}
			set
			{
				if ((this._TodoDescSecondary != value))
				{
					this.OnTodoDescSecondaryChanging(value);
					this.SendPropertyChanging();
					this._TodoDescSecondary = value;
					this.SendPropertyChanged("TodoDescSecondary");
					this.OnTodoDescSecondaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TodoDueDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TodoDueDate
		{
			get
			{
				return this._TodoDueDate;
			}
			set
			{
				if ((this._TodoDueDate != value))
				{
					this.OnTodoDueDateChanging(value);
					this.SendPropertyChanging();
					this._TodoDueDate = value;
					this.SendPropertyChanged("TodoDueDate");
					this.OnTodoDueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskCompleted", DbType="Bit")]
		public System.Nullable<bool> TaskCompleted
		{
			get
			{
				return this._TaskCompleted;
			}
			set
			{
				if ((this._TaskCompleted != value))
				{
					this.OnTaskCompletedChanging(value);
					this.SendPropertyChanging();
					this._TaskCompleted = value;
					this.SendPropertyChanged("TaskCompleted");
					this.OnTaskCompletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
